version: '3.8'
services:
  database-comanda-eletronica:   
    image: postgres
    container_name: database-comanda-eletronica 
    ports:
      - 5432:5432
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=db-comanda-eletronica
    volumes:
      - pgdata:/data/postgres
#   pgadmin:
#     container_name: pgadmin4_container
#     image: dpage/pgadmin4
#     restart: always
#     networks:
#       - api-nodejs_default
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports:
#       - "5050:80"
#     network_mode: host

# networks:
#   api-nodejs_default:
#     external: true 

volumes:
  pgdata:
    driver: local